name: PyInstaller Action
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --icon "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/icon-win.ico" --name "SMDTools" --add-data "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/version.txt:." --add-data "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/LICENSE:." --add-data "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/README.md:." --add-data "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/save:save/" --add-data "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/scripts:scripts/"  "/home/postscript/Desktop/Github Repos/PS-s-SMD-Tools/GUI.py"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMDTools
          path: dist/SMDTools
