name: PyInstaller Action
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --icon "icon-win.ico" --name "SMDTools" --add-data "version.txt:." --add-data "LICENSE:." --add-data "README.md:." --add-data "save:save/" --add-data "scripts:scripts/"  "GUI.py"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMDTools
          path: dist/SMDTools
